// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperTraders.Data;

#nullable disable

namespace SuperTraders.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220125194154_Order")]
    partial class Order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperTraders.Core.Entities.BuyOrder", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTransactionPerformed")
                        .HasColumnType("boolean");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("integer");

                    b.Property<string>("ShareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShareId");

                    b.HasIndex("UserId");

                    b.ToTable("BuyOrders");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.SellOrder", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTransactionPerformed")
                        .HasColumnType("boolean");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("integer");

                    b.Property<string>("ShareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShareId");

                    b.HasIndex("UserId");

                    b.ToTable("SellOrders");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.Share", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Shares");

                    b.HasData(
                        new
                        {
                            Id = "8d238de0-1f08-4fc0-b49d-febdea62dc67",
                            Code = "LIP",
                            Name = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = "7ec214a8-252e-4b5b-96d9-bff6bc87caae",
                            Code = "DSA",
                            Name = "Dolor Sit Amer"
                        },
                        new
                        {
                            Id = "b1e7f7ca-5353-4071-a308-09fcca0efe94",
                            Code = "CAE",
                            Name = "Consectetur Adipiscing Elit"
                        });
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("BuyOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuyOrderId")
                        .IsUnique();

                    b.HasIndex("SellOrderId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEMailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "d697322e-bc77-4c3f-ad29-0388b5949b06",
                            AuthToken = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiIiwibmJmIjoxNjQzMTM1NDU0LCJleHAiOjE2NDU3Mjc0NTQsImlhdCI6MTY0MzEzNTQ1NH0.jb-M5NOTieF1GDR1mHsc9YtFLKUB4uSjZVSfZbh-APg",
                            EMail = "osman@zulfigaroglu.com",
                            IsEMailVerified = false,
                            Password = "123456",
                            UserName = "osman"
                        },
                        new
                        {
                            Id = "6027a78b-5feb-489e-94ca-615c5434bfa0",
                            AuthToken = "",
                            EMail = "lorem@ipsum.com",
                            IsEMailVerified = false,
                            Password = "123456",
                            UserName = "lorem"
                        },
                        new
                        {
                            Id = "10e5b64b-6584-41d3-b559-15303e09dff3",
                            AuthToken = "",
                            EMail = "dolor@sitamet.com",
                            IsEMailVerified = false,
                            Password = "123456",
                            UserName = "dolor"
                        });
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.UserShare", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("ShareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShareId");

                    b.HasIndex("UserId");

                    b.ToTable("UserShare");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.BuyOrder", b =>
                {
                    b.HasOne("SuperTraders.Core.Entities.Share", "Share")
                        .WithMany()
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperTraders.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Share");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.SellOrder", b =>
                {
                    b.HasOne("SuperTraders.Core.Entities.Share", "Share")
                        .WithMany()
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperTraders.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Share");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.Transaction", b =>
                {
                    b.HasOne("SuperTraders.Core.Entities.BuyOrder", "BuyOrder")
                        .WithOne("Transaction")
                        .HasForeignKey("SuperTraders.Core.Entities.Transaction", "BuyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperTraders.Core.Entities.SellOrder", "SellOrder")
                        .WithOne("Transaction")
                        .HasForeignKey("SuperTraders.Core.Entities.Transaction", "SellOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyOrder");

                    b.Navigation("SellOrder");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.UserShare", b =>
                {
                    b.HasOne("SuperTraders.Core.Entities.Share", "Share")
                        .WithMany("UserShares")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperTraders.Core.Entities.User", "User")
                        .WithMany("UserShares")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Share");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.BuyOrder", b =>
                {
                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.SellOrder", b =>
                {
                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.Share", b =>
                {
                    b.Navigation("UserShares");
                });

            modelBuilder.Entity("SuperTraders.Core.Entities.User", b =>
                {
                    b.Navigation("UserShares");
                });
#pragma warning restore 612, 618
        }
    }
}
